[package]
name = "retro-frontend-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
libloading = "0.8"

[build-dependencies]
bindgen = "0.70.1"
reqwest = { version = "0.12.7", features = ["blocking"] }
